export enum ProductCategory {
  ELECTRONICS = 'ELECTRONICS',
  FASHION = 'FASHION',
  BOOKS = 'BOOKS',
  HOME = 'HOME',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  TOYS = 'TOYS',
  GROCERY = 'GROCERY',
  AUTOMOTIVE = 'AUTOMOTIVE',
  STATIONERY = 'STATIONERY',
  HEALTH = 'HEALTH',
  PET_SUPPLIES = 'PET_SUPPLIES'
}
