spring.application.name=Gateway
spring.cloud.gateway.mvc.routes[0].id=product-service
spring.cloud.gateway.mvc.routes[0].uri=lb://product
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/products/**
